companieshouse/accounts-association-api

ecs-image-build/docker_start.sh

Changes to Docker start.sh

---

pom.xml

Fixed small bug in pom

---

terraform/groups/ecs-service/data.tf
terraform/groups/ecs-service/locals.tf
terraform/groups/ecs-service/main.tf
terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars
terraform/groups/ecs-service/profiles/development-eu-west-2/phoenix1/vars
terraform/groups/ecs-service/variables.tf

Refactoring Terraform folder

---

terraform/groups/ecs-service/locals.tf
terraform/groups/ecs-service/main.tf
terraform/groups/ecs-service/variables.tf

Adding  eric config

---

terraform/groups/ecs-service/locals.tf

chaning docker_start.sh file permission

---

terraform/groups/ecs-service/main.tf

Adding few eric config

---

suppress.xml

Updated suppress file.

---

terraform/groups/ecs-service/main.tf

Fixing terraform

---

terraform/groups/ecs-service/main.tf

Changing the terraform module version

---

terraform/groups/ecs-service/main.tf
terraform/groups/ecs-service/variables.tf

Refactoring ECS config

---

terraform/groups/ecs-service/variables.tf

Changes memory and cpu values

---

routes.yaml
src/main/resources/application.properties

change properties to match vault and ecs config
* [ *] Infrastructure change

amend property file

---

Tiltfile.dev
routes.yaml
src/main/java/uk/gov/companieshouse/accounts/association/configuration/InterceptorConfig.java
src/test/java/uk/gov/companieshouse/accounts/association/controllers/ControllerAdviceTest.java
src/test/java/uk/gov/companieshouse/accounts/association/controllers/UserCompanyAssociationStatusApiTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/UserCompanyAssociationStatusApiTest.java

Fixed some bugs in Tiltfile.dev and routes.yaml. Added the Eric interceptor, and updated tests accordingly.
IDVA6-471

Idva6 471 adding eric interceptors

---

src/main/java/uk/gov/companieshouse/accounts/association/repositories/AssociationsRepository.java
src/main/resources/application.properties
src/test/java/uk/gov/companieshouse/accounts/association/integration/AssociationsServiceTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/UserCompanyAssociationStatusApiTest.java
src/test/java/uk/gov/companieshouse/accounts/association/repositories/AssociationsRepositoryTest.java

add support to pageable dynamic search on company number

---

src/main/java/uk/gov/companieshouse/accounts/association/mapper/AssociationCompanyDaoToDtoMapper.java
src/main/java/uk/gov/companieshouse/accounts/association/mapper/AssociationUserDaoToDtoMapper.java
src/main/java/uk/gov/companieshouse/accounts/association/mapper/AssociationsListCompanyDaoToDtoMapper.java
src/main/java/uk/gov/companieshouse/accounts/association/mapper/AssociationsListUserDaoToDtoMapper.java
src/main/java/uk/gov/companieshouse/accounts/association/mapper/abstracts/AssociationDaoToDtoMapper.java
src/main/java/uk/gov/companieshouse/accounts/association/mapper/abstracts/AssociationsListDaoToDtoMapper.java
src/main/java/uk/gov/companieshouse/accounts/association/models/Association.java
src/main/java/uk/gov/companieshouse/accounts/association/service/CompanyService.java
src/main/java/uk/gov/companieshouse/accounts/association/service/UsersService.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/AssociationsServiceTest.java
src/test/java/uk/gov/companieshouse/accounts/association/mapper/AssociationCompanyDaoToDtoMapperTest.java
src/test/java/uk/gov/companieshouse/accounts/association/mapper/AssociationUserDaoToDtoMapperTest.java
src/test/java/uk/gov/companieshouse/accounts/association/mapper/AssociationsListCompanyDaoToDtoMapperTest.java
src/test/java/uk/gov/companieshouse/accounts/association/mapper/AssociationsListUserDaoToDtoMapperTest.java
src/test/java/uk/gov/companieshouse/accounts/association/mapper/abstracts/AssociationDaoToDtoMapperTest.java
src/test/java/uk/gov/companieshouse/accounts/association/mapper/abstracts/AssociationsListDaoToDtoMapperTest.java
src/test/java/uk/gov/companieshouse/accounts/association/repositories/AssociationsRepositoryTest.java
src/test/java/uk/gov/companieshouse/accounts/association/service/CompanyServiceTest.java
src/test/java/uk/gov/companieshouse/accounts/association/service/UsersServiceTest.java
src/test/resources/application.properties

Added enrichment mappers.
IDVA6-647

Idva6 647 association enrichment mapper

---

terraform/groups/ecs-service/main.tf

Changing terraform module version

---

src/main/resources/application.properties

properties change

---

terraform/groups/ecs-service/locals.tf

Path change

---

src/main/java/uk/gov/companieshouse/accounts/association/controller/AssociationsListForCompanyController.java
src/main/java/uk/gov/companieshouse/accounts/association/controller/UserCompanyAssociations.java
src/main/java/uk/gov/companieshouse/accounts/association/service/AssociationsService.java
src/test/java/uk/gov/companieshouse/accounts/association/controller/AssociationsListForCompanyControllerTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/AssociationsListForCompanyControllerTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/AssociationsServiceTest.java

New endpoint to fetch associations for a company
IDVA6-494

Idva6 494 merge

---

src/main/java/uk/gov/companieshouse/accounts/association/controller/ControllerAdvice.java
src/main/java/uk/gov/companieshouse/accounts/association/controller/UserCompanyAssociations.java
src/test/java/uk/gov/companieshouse/accounts/association/controller/ControllerAdviceTest.java

Idva6 707 controller advice testss

---

src/main/java/uk/gov/companieshouse/accounts/association/AccountsAssociationServiceApplication.java
src/main/java/uk/gov/companieshouse/accounts/association/configuration/InterceptorConfig.java
src/main/java/uk/gov/companieshouse/accounts/association/controller/AssociationsListForCompanyController.java
src/main/java/uk/gov/companieshouse/accounts/association/controller/ControllerAdvice.java
src/main/java/uk/gov/companieshouse/accounts/association/controller/UserCompanyAssociations.java
src/main/java/uk/gov/companieshouse/accounts/association/interceptor/AuthorizationInterceptor.java
src/main/java/uk/gov/companieshouse/accounts/association/interceptor/LoggingInterceptor.java
src/main/java/uk/gov/companieshouse/accounts/association/models/AssociationDao.java
src/main/java/uk/gov/companieshouse/accounts/association/models/InvitationDao.java
src/main/java/uk/gov/companieshouse/accounts/association/service/CompanyService.java
src/main/java/uk/gov/companieshouse/accounts/association/service/UsersService.java
src/main/java/uk/gov/companieshouse/accounts/association/utils/StaticPropertyUtil.java
src/test/java/uk/gov/companieshouse/accounts/association/controller/AssociationsListForCompanyControllerTest.java
src/test/java/uk/gov/companieshouse/accounts/association/controller/ControllerAdviceTest.java
src/test/java/uk/gov/companieshouse/accounts/association/controller/UserCompanyAssociationsTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/AssociationsListForCompanyControllerTest.java
src/test/java/uk/gov/companieshouse/accounts/association/interceptor/AuthorizationInterceptorTest.java
src/test/java/uk/gov/companieshouse/accounts/association/mapper/AssociationMapperTest.java
src/test/java/uk/gov/companieshouse/accounts/association/mapper/AssociationsListCompanyMapperTest.java
src/test/java/uk/gov/companieshouse/accounts/association/rest/AccountsUserEndpointTest.java
src/test/resources/application.properties

fix interceptor
fix static property
fix sonar issues

fix oauth interceptor

---

terraform/groups/ecs-service/locals.tf

change lb path

---

pom.xml
src/test/java/uk/gov/companieshouse/accounts/association/controller/UserCompanyAssociationsTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/AssociationsRepositoryTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/AssociationsServiceTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/UserCompanyAssociationsTest.java
src/test/java/uk/gov/companieshouse/accounts/association/service/AssociationsServiceTest.java

Tests for search endpoint
IDVA6-678

Added tests for search endpoint

---

src/main/java/uk/gov/companieshouse/accounts/association/controller/ControllerAdvice.java
src/main/java/uk/gov/companieshouse/accounts/association/controller/UserCompanyAssociations.java
src/main/java/uk/gov/companieshouse/accounts/association/interceptor/AuthorizationInterceptor.java
src/main/java/uk/gov/companieshouse/accounts/association/service/AssociationsService.java
src/test/java/uk/gov/companieshouse/accounts/association/controller/UserCompanyAssociationsTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/UserCompanyAssociationsTest.java
src/test/java/uk/gov/companieshouse/accounts/association/service/AssociationsServiceTest.java

get Association endpoint

---

pom.xml
src/main/java/uk/gov/companieshouse/accounts/association/controller/AssociationsListForCompanyController.java
src/main/java/uk/gov/companieshouse/accounts/association/repositories/AssociationsRepository.java
src/main/java/uk/gov/companieshouse/accounts/association/service/AssociationsService.java
src/test/java/uk/gov/companieshouse/accounts/association/controller/AssociationsListForCompanyControllerTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/AssociationsListForCompanyControllerTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/AssociationsRepositoryTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/AssociationsServiceTest.java
src/test/java/uk/gov/companieshouse/accounts/association/service/AssociationsServiceTest.java

Changes were made to the /associations/companies/{company_number} endpoint. The endpoint now has an additional, optional filter that can be applied based on the user's email address.
IDVA6-761

Idva6 761 fetch associations for company with email

---

src/main/java/uk/gov/companieshouse/accounts/association/controller/UserCompanyAssociations.java
src/main/java/uk/gov/companieshouse/accounts/association/models/AssociationDao.java
src/main/java/uk/gov/companieshouse/accounts/association/repositories/AssociationsRepository.java
src/main/java/uk/gov/companieshouse/accounts/association/service/AssociationsService.java
src/main/java/uk/gov/companieshouse/accounts/association/service/UsersService.java
src/test/java/uk/gov/companieshouse/accounts/association/controller/UserCompanyAssociationsTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/AssociationsRepositoryTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/AssociationsServiceTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/UserCompanyAssociationsTest.java
src/test/java/uk/gov/companieshouse/accounts/association/service/AssociationsServiceTest.java
src/test/java/uk/gov/companieshouse/accounts/association/service/UsersServiceTest.java

An endpoint to update the status of an association.
IDVA6-548

Idva6 548 update status

---

src/main/java/uk/gov/companieshouse/accounts/association/controller/UserCompanyAssociations.java
src/main/java/uk/gov/companieshouse/accounts/association/repositories/AssociationsRepository.java
src/main/java/uk/gov/companieshouse/accounts/association/service/AssociationsService.java
src/test/java/uk/gov/companieshouse/accounts/association/controller/UserCompanyAssociationsTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/AssociationsRepositoryTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/AssociationsServiceTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/UserCompanyAssociationsTest.java
src/test/java/uk/gov/companieshouse/accounts/association/service/AssociationsServiceTest.java

Endpoint to create invitations.
IDVA6-679

Idva6 679 invite user

---

pom.xml
src/main/java/uk/gov/companieshouse/accounts/association/controller/AssociationsListForCompanyController.java
src/main/java/uk/gov/companieshouse/accounts/association/service/AssociationsService.java
src/test/java/uk/gov/companieshouse/accounts/association/controller/AssociationsListForCompanyControllerTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/AssociationsListForCompanyControllerTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/AssociationsServiceTest.java
src/test/java/uk/gov/companieshouse/accounts/association/service/AssociationsServiceTest.java

changes to remove email filter on company users get

---

pom.xml
src/main/java/uk/gov/companieshouse/accounts/association/models/email/AuthCodeConfirmationEmailData.java
src/main/java/uk/gov/companieshouse/accounts/association/models/email/AuthorisationRemovedEmailData.java
src/main/java/uk/gov/companieshouse/accounts/association/models/email/InvitationAcceptedEmailData.java
src/main/java/uk/gov/companieshouse/accounts/association/models/email/InvitationCancelledEmailData.java
src/main/java/uk/gov/companieshouse/accounts/association/models/email/InvitationEmailData.java
src/main/java/uk/gov/companieshouse/accounts/association/models/email/InvitationRejectedEmailData.java
src/main/java/uk/gov/companieshouse/accounts/association/service/EmailService.java
src/main/java/uk/gov/companieshouse/accounts/association/utils/Constants.java
src/main/resources/application.properties
src/test/java/uk/gov/companieshouse/accounts/association/integration/AssociationsListForCompanyControllerTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/AssociationsRepositoryTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/AssociationsServiceTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/UserCompanyAssociationsTest.java
src/test/java/uk/gov/companieshouse/accounts/association/service/EmailServiceTest.java

An email service that can be used to send one of six email types.
IDVA6-790

Idva6 790 email producer

---

terraform/groups/ecs-service/data.tf

Chaning Load Balancer

---

src/main/java/uk/gov/companieshouse/accounts/association/controller/UserCompanyAssociations.java

Fixed logging

---

src/main/java/uk/gov/companieshouse/accounts/association/controller/UserCompanyAssociations.java
src/main/java/uk/gov/companieshouse/accounts/association/models/email/EmailNotification.java
src/main/java/uk/gov/companieshouse/accounts/association/service/EmailService.java
src/test/java/uk/gov/companieshouse/accounts/association/controller/ControllerAdviceTest.java
src/test/java/uk/gov/companieshouse/accounts/association/controller/UserCompanyAssociationsTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/UserCompanyAssociationsTest.java

Added functionality to send notifications in addAssociation endpoint.
IDVA6-430

Idva6 430 bulk email sender in add association v2

---

src/main/java/uk/gov/companieshouse/accounts/association/controller/UserCompanyAssociations.java
src/test/java/uk/gov/companieshouse/accounts/association/controller/UserCompanyAssociationsTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/UserCompanyAssociationsTest.java

Invite Email

---

src/main/resources/application.properties

fix application properties

---

src/main/java/uk/gov/companieshouse/accounts/association/controller/UserCompanyAssociations.java
src/main/java/uk/gov/companieshouse/accounts/association/service/EmailService.java
src/test/java/uk/gov/companieshouse/accounts/association/controller/UserCompanyAssociationsTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/UserCompanyAssociationsTest.java
src/test/java/uk/gov/companieshouse/accounts/association/service/EmailServiceTest.java

Integrated invite email into invitation endpoint

---

src/main/java/uk/gov/companieshouse/accounts/association/controller/UserCompanyAssociations.java
src/main/java/uk/gov/companieshouse/accounts/association/service/AssociationsService.java
src/test/java/uk/gov/companieshouse/accounts/association/controller/UserCompanyAssociationsTest.java
src/test/java/uk/gov/companieshouse/accounts/association/service/AssociationsServiceTest.java

- Implemented the 'get invitations from association id' endpoint
- Added some basic test coverage for the endpoint & `fetchInvitations` method

IDVA6-1069: Get invitations from association id

---

src/main/java/uk/gov/companieshouse/accounts/association/service/AssociationsService.java

Refactoring

---

pom.xml
src/main/java/uk/gov/companieshouse/accounts/association/controller/UserCompanyAssociations.java
src/main/java/uk/gov/companieshouse/accounts/association/service/AssociationsService.java
src/test/java/uk/gov/companieshouse/accounts/association/controller/UserCompanyAssociationsTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/AssociationsServiceTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/UserCompanyAssociationsTest.java
src/test/java/uk/gov/companieshouse/accounts/association/service/AssociationsServiceTest.java

Replaced `List<Invitation>` with `InvitationsList` in the `UserCompanyAssociations` controller and `AssociationsService` service. Updated the pom.xml file to use the latest version of `private-api-sdk-java`.
[IDVA6-1103](https://companieshouse.atlassian.net/browse/IDVA6-1103)
[IDVA6-1103]: https://companieshouse.atlassian.net/browse/IDVA6-1103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IDVA6-1103: Replace List<Invitation> with InvitationsList

---

src/main/java/uk/gov/companieshouse/accounts/association/service/AssociationsService.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/AssociationsServiceTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/UserCompanyAssociationsTest.java

- Ensure invitations are sorted descending by association expiry date

Ensure invitations are sorted descending by association expiry date

---

src/main/java/uk/gov/companieshouse/accounts/association/controller/UserCompanyAssociations.java
src/main/java/uk/gov/companieshouse/accounts/association/repositories/AssociationsRepository.java
src/main/java/uk/gov/companieshouse/accounts/association/service/AssociationsService.java
src/test/java/uk/gov/companieshouse/accounts/association/controller/UserCompanyAssociationsTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/AssociationsRepositoryTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/AssociationsServiceTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/UserCompanyAssociationsTest.java
src/test/java/uk/gov/companieshouse/accounts/association/service/AssociationsServiceTest.java

This PR updates the association service to check for confirmed associations instead of any associations. The changes include method renaming for clarity and updating the corresponding tests and validation logic.
__JIRA Ticket Number__: IDVA6-1117

IDVA6-1117: Update Association Service to Check for Confirmed Associations

---

src/main/java/uk/gov/companieshouse/accounts/association/controller/UserCompanyAssociations.java
src/main/java/uk/gov/companieshouse/accounts/association/repositories/AssociationsRepository.java
src/main/java/uk/gov/companieshouse/accounts/association/service/AssociationsService.java
src/test/java/uk/gov/companieshouse/accounts/association/controller/UserCompanyAssociationsTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/AssociationsRepositoryTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/AssociationsServiceTest.java
src/test/java/uk/gov/companieshouse/accounts/association/service/AssociationsServiceTest.java

* Updated the method for creating associations to use an upsert operation.
* Ensured existing associations are updated instead of creating duplicates.
* Refactored tests to replace `createAssociation` with `upsertAssociation`.
* Added parameterized tests for null and malformed input validation.
[IDVA6-1129](https://companieshouse.atlassian.net/browse/IDVA6-1129)
[IDVA6-1129]: https://companieshouse.atlassian.net/browse/IDVA6-1129?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IDVA6-1129: Upsert Association Changes

---

src/main/java/uk/gov/companieshouse/accounts/association/controller/ControllerAdvice.java
src/main/java/uk/gov/companieshouse/accounts/association/controller/UserCompanyAssociations.java
src/main/java/uk/gov/companieshouse/accounts/association/models/InvitationDao.java
src/main/java/uk/gov/companieshouse/accounts/association/models/UserContext.java
src/main/java/uk/gov/companieshouse/accounts/association/service/EmailService.java
src/main/java/uk/gov/companieshouse/accounts/association/utils/MessageType.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/AssociationsRepositoryTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/UserCompanyAssociationsTest.java
src/test/java/uk/gov/companieshouse/accounts/association/models/email/builders/InviteEmailBuilderTest.java
src/test/java/uk/gov/companieshouse/accounts/association/service/AssociationsServiceTest.java
src/test/java/uk/gov/companieshouse/accounts/association/service/EmailServiceTest.java
src/test/java/uk/gov/companieshouse/accounts/association/service/UsersServiceTest.java

Update Security Dependencies

---

src/main/java/uk/gov/companieshouse/accounts/association/controller/UserCompanyAssociations.java
src/main/java/uk/gov/companieshouse/accounts/association/models/email/builders/YourAuthorisationRemovedEmailBuilder.java
src/main/java/uk/gov/companieshouse/accounts/association/models/email/data/YourAuthorisationRemovedEmailData.java
src/main/java/uk/gov/companieshouse/accounts/association/service/EmailService.java
src/main/java/uk/gov/companieshouse/accounts/association/utils/MessageType.java

__Short description outlining key changes/additions:__
- Added functionality to notify removed users of their removal.
- Updated association methods to include user email details.
- Enhanced email service to handle new removal notification emails.
- Introduced `YourAuthorisationRemovedEmailBuilder` and `YourAuthorisationRemovedEmailData` for email construction.
- Modified `sendEmailNotificationForStatusUpdate` to support notification to removed users.
- Added unit tests for the new email notification functionality.
__JIRA Ticket Number:__ IDVA6-1075

IDVA6-1075: Notify removed user of their removal

---

src/main/resources/application.properties
src/test/java/uk/gov/companieshouse/accounts/association/integration/UserCompanyAssociationsTest.java

Tferns idva6 1129 bug fix

---

src/test/java/uk/gov/companieshouse/accounts/association/integration/UserCompanyAssociationsTest.java

fix race issue

---

src/main/java/uk/gov/companieshouse/accounts/association/controller/UserCompanyAssociations.java
src/main/java/uk/gov/companieshouse/accounts/association/service/AssociationsService.java
src/test/java/uk/gov/companieshouse/accounts/association/controller/UserCompanyAssociationsTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/AssociationsServiceTest.java
src/test/java/uk/gov/companieshouse/accounts/association/service/AssociationsServiceTest.java

association post should allow the existing association to be overriden when using post.

idva6-1129

---

pom.xml

IDVA6-1227: Update to Spring Boot 3.3

---

src/main/java/uk/gov/companieshouse/accounts/association/controller/UserCompanyAssociations.java

idva6-1204 change approval route to authcode for post

---

src/main/resources/application.properties

move chs internal api key to use new accounts user api key

move chs internal api key to use new accounts user api key

---

pom.xml

bump up private api sdk version

bump up private api sdk version

---

terraform/groups/ecs-service/variables.tf

Setting variable to true

---

pom.xml
src/main/java/uk/gov/companieshouse/accounts/association/utils/ApiClientUtil.java
src/main/resources/application.properties
src/test/java/uk/gov/companieshouse/accounts/association/integration/AssociationsListForCompanyControllerTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/AssociationsServiceTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/UserCompanyAssociationsTest.java

fix users api call to use account endpoint

fix users api call to use account endpoint

---

src/main/java/uk/gov/companieshouse/accounts/association/rest/AccountsUserEndpoint.java
src/main/java/uk/gov/companieshouse/accounts/association/utils/ApiClientUtil.java

adding temp loggers

---

src/main/java/uk/gov/companieshouse/accounts/association/rest/AccountsUserEndpoint.java

converting to info context

---

src/main/java/uk/gov/companieshouse/accounts/association/rest/AccountsUserEndpoint.java
src/main/resources/application.properties

changing spring keys

---

src/main/java/uk/gov/companieshouse/accounts/association/configuration/ApiClientConfig.java
src/main/java/uk/gov/companieshouse/accounts/association/utils/ApiClientUtil.java
src/test/resources/application.properties

amend api client config to take multiple endpoints with new api key

amend api client config to take multiple endpoints with new api key

---

src/main/resources/application.properties

Fixed config issues
IDVA6-1296

Fixed config issues

---

pom.xml

Updated pom.xml so that it will use the latest sonar.
IDVA6-1306

Updated pom

---

src/main/java/uk/gov/companieshouse/accounts/association/controller/UserCompanyAssociations.java
src/main/java/uk/gov/companieshouse/accounts/association/models/email/builders/InviteCancelledEmailBuilder.java
src/main/java/uk/gov/companieshouse/accounts/association/models/email/data/InviteCancelledEmailData.java
src/main/java/uk/gov/companieshouse/accounts/association/service/EmailService.java
src/main/java/uk/gov/companieshouse/accounts/association/utils/MessageType.java
src/test/java/uk/gov/companieshouse/accounts/association/models/email/builders/InviteCancelledEmailBuilderTest.java
src/test/java/uk/gov/companieshouse/accounts/association/service/EmailServiceTest.java

Created new notification, for sending cancelled invite email
IDVA6-1249

Added notification for cancelled invite

---

pom.xml
src/test/java/uk/gov/companieshouse/accounts/association/controller/UserCompanyAssociationsTest.java
src/test/java/uk/gov/companieshouse/accounts/association/service/AssociationsServiceTest.java

- Upgrade Spring Boot from 3.3.1 to 3.3.2
- Update various library versions:
- structured-logging to 3.0.10
- private-api-sdk-java to 4.0.185
- api-security-java to 2.0.6
- mapstruct to 1.6.0.RC1
- junit-jupiter (TestContainers) to 1.20.1
- kafka-clients to 3.8.0
- sonar-maven-plugin to 4.0.0.4121
- Add version properties for junit, commons-compress, google-http-client, api-helper-java, and email-producer-java
- Refactor dependency versions to use properties for consistency

IDVA6-1418: Update dependencies and refactor version properties

---

pom.xml
src/test/java/uk/gov/companieshouse/accounts/association/integration/AssociationsListForCompanyControllerTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/AssociationsRepositoryTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/AssociationsServiceTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/UserCompanyAssociationsTest.java
src/test/resources/application.properties

Replaced TestContainers with Flapdoodle.
IDVA6-1411

Replaced TestContainers with Flapdoodle.

---

terraform/groups/ecs-service/profiles/staging-eu-west-2/staging/vars

Added staging profile
IDVA6-1439

Added staging profile.

---

terraform/groups/ecs-service/main.tf
terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars
terraform/groups/ecs-service/profiles/development-eu-west-2/phoenix1/vars
terraform/groups/ecs-service/profiles/staging-eu-west-2/staging/vars
terraform/groups/ecs-service/variables.tf

Update TF ECS modules, tf values, scheduling and autoscaling
[DVOP-3015](https://companieshouse.atlassian.net/browse/DVOP-3015)
[DVOP-3015]: https://companieshouse.atlassian.net/browse/DVOP-3015?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

updating tf ecs modules

---

pom.xml

Updated version of kafka-clients
IDVA6-1484

Updated kafka-clients version

---

pom.xml
src/main/java/uk/gov/companieshouse/accounts/association/mapper/AssociationMapper.java
src/main/java/uk/gov/companieshouse/accounts/association/mapper/AssociationsListCompanyMapper.java
src/main/java/uk/gov/companieshouse/accounts/association/mapper/AssociationsListUserMapper.java
src/main/java/uk/gov/companieshouse/accounts/association/utils/MapperUtil.java
src/test/java/uk/gov/companieshouse/accounts/association/common/TestDataManager.java
src/test/java/uk/gov/companieshouse/accounts/association/mapper/AssociationMapperTest.java
src/test/java/uk/gov/companieshouse/accounts/association/mapper/AssociationsListCompanyMapperTest.java
src/test/java/uk/gov/companieshouse/accounts/association/mapper/AssociationsListUserMapperTest.java

Added company_status to Association
IDVA6-1485

Added company_status to Association

---

src/main/java/uk/gov/companieshouse/accounts/association/controller/ControllerAdvice.java
src/main/java/uk/gov/companieshouse/accounts/association/controller/UserCompanyAssociations.java
src/main/java/uk/gov/companieshouse/accounts/association/service/AssociationsService.java
src/main/java/uk/gov/companieshouse/accounts/association/utils/StaticPropertyUtil.java
src/test/java/uk/gov/companieshouse/accounts/association/common/Mockers.java
src/test/java/uk/gov/companieshouse/accounts/association/controller/AssociationsListForCompanyControllerTest.java
src/test/java/uk/gov/companieshouse/accounts/association/controller/UserCompanyAssociationsTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/AssociationsRepositoryTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/AssociationsServiceTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/UserCompanyAssociationsTest.java
src/test/java/uk/gov/companieshouse/accounts/association/mapper/AssociationMapperTest.java
src/test/java/uk/gov/companieshouse/accounts/association/models/email/builders/AuthCodeConfirmationEmailBuilderTest.java
src/test/java/uk/gov/companieshouse/accounts/association/models/email/builders/AuthorisationRemovedEmailBuilderTest.java
src/test/java/uk/gov/companieshouse/accounts/association/models/email/builders/InvitationAcceptedEmailBuilderTest.java
src/test/java/uk/gov/companieshouse/accounts/association/models/email/builders/InvitationCancelledEmailBuilderTest.java
src/test/java/uk/gov/companieshouse/accounts/association/models/email/builders/InvitationEmailBuilderTest.java
src/test/java/uk/gov/companieshouse/accounts/association/models/email/builders/InvitationRejectedEmailBuilderTest.java
src/test/java/uk/gov/companieshouse/accounts/association/rest/AccountsUserEndpointTest.java
src/test/java/uk/gov/companieshouse/accounts/association/service/AssociationsServiceTest.java
src/test/java/uk/gov/companieshouse/accounts/association/service/EmailServiceTest.java
src/test/java/uk/gov/companieshouse/accounts/association/service/UsersServiceTest.java

Implemented sonar fixes
IDVA6-1555

Implemented sonar fixes

---

pom.xml
src/main/java/uk/gov/companieshouse/accounts/association/mapper/AssociationMapper.java
src/test/java/uk/gov/companieshouse/accounts/association/common/TestDataManager.java
src/test/java/uk/gov/companieshouse/accounts/association/mapper/AssociationMapperTest.java

Changed company_status's type from enum to string
IDVA6-1485

IDVA6-1485: Change company_status's type from enum to string

---

pom.xml
suppress.xml

Updated versions of all dependencies.
IDVA6-1792

IDVA6-1792: Updated versions of all dependencies.

---

pom.xml

IDVA6-1924: Updated parent pom

---

pom.xml
suppress.xml

Upgraded Spring to the latest version, and addressed security failures.
IDVA6-1925

IDVA6-1925: Upgraded Spring to the latest version, and addressed security failures.

---

pom.xml
suppress.xml

Updated suppressions to include only minimalist suppressions
IDVA6-1941

IDVA6-1941: Updated suppressions to include only minimalist suppressions

---

pom.xml
src/main/java/uk/gov/companieshouse/accounts/association/controller/AssociationsListForCompanyController.java
src/main/java/uk/gov/companieshouse/accounts/association/controller/UserCompanyAssociations.java
src/main/java/uk/gov/companieshouse/accounts/association/models/email/EmailNotification.java
src/main/java/uk/gov/companieshouse/accounts/association/service/AssociationsService.java
src/main/java/uk/gov/companieshouse/accounts/association/service/CompanyService.java
src/main/java/uk/gov/companieshouse/accounts/association/service/EmailService.java
src/main/java/uk/gov/companieshouse/accounts/association/service/UsersService.java
src/main/java/uk/gov/companieshouse/accounts/association/utils/RequestContextUtil.java
src/test/java/uk/gov/companieshouse/accounts/association/controller/UserCompanyAssociationsTest.java

Added new logging and updated existing logging
IDVA6-1953

IDVA6-1953: Added new logging and updated existing logging

---

pom.xml

Updated email regex.
IDVA6-2022

IDVA6-2022: Updated email regex.

---

terraform/groups/ecs-service/profiles/live-eu-west-2/live/vars

Adding live env

---

Makefile
pom.xml

IDVA6-2214: Upgrading sonar

---

src/main/java/uk/gov/companieshouse/accounts/association/service/EmailService.java

IDVA6-2232: Bug fix

---

README.md
pom.xml
suppress.xml

IDVA6-2295: Security fixes

---

src/main/java/uk/gov/companieshouse/accounts/association/service/AssociationsService.java
src/test/java/uk/gov/companieshouse/accounts/association/controller/AssociationsListForCompanyControllerTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/AssociationsListForCompanyControllerTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/AssociationsServiceTest.java
src/test/java/uk/gov/companieshouse/accounts/association/service/AssociationsServiceTest.java

Updated getAssociationsForCompany so that it can fetch migrated associations
IDVA6-2041

IDVA6-2041: Data Migration - getAssociationsForCompany

---

src/main/java/uk/gov/companieshouse/accounts/association/controller/UserCompanyAssociations.java
src/test/java/uk/gov/companieshouse/accounts/association/controller/UserCompanyAssociationsTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/UserCompanyAssociationsTest.java

Updated addAssociation so that it can work with migrated associations.
IDVA6-2039

IDVA6-2039: Updated addAssociation so that it can work with migrated associations. 

---

src/main/java/uk/gov/companieshouse/accounts/association/service/AssociationsService.java
src/test/java/uk/gov/companieshouse/accounts/association/controller/UserCompanyInvitationsTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/AssociationsServiceTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/UserCompanyInvitationsTest.java
src/test/java/uk/gov/companieshouse/accounts/association/service/AssociationsServiceTest.java

Updated inviteUser so that it can work with migrated associations.
IDVA6-2040

IDVA6-2040: Updated inviteUser so that it can work with migrated associations.

---

src/main/java/uk/gov/companieshouse/accounts/association/controller/UserCompanyAssociation.java
src/main/java/uk/gov/companieshouse/accounts/association/utils/AssociationsUtil.java
src/main/java/uk/gov/companieshouse/accounts/association/utils/UserUtil.java
src/test/java/uk/gov/companieshouse/accounts/association/common/TestDataManager.java
src/test/java/uk/gov/companieshouse/accounts/association/controller/UserCompanyAssociationTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/UserCompanyAssociationTest.java
src/test/java/uk/gov/companieshouse/accounts/association/utils/AssociationsUtilTest.java
src/test/java/uk/gov/companieshouse/accounts/association/utils/UserUtilTest.java

Updated patch endpoint so that it can work with migrated associations.
IDVA6-2042

Idva6-2042 Data Migration Patch Association

---

src/main/java/uk/gov/companieshouse/accounts/association/controller/UserCompanyAssociation.java
src/main/java/uk/gov/companieshouse/accounts/association/mapper/PreviousStatesCollectionMappers.java
src/main/java/uk/gov/companieshouse/accounts/association/mapper/PreviousStatesMapper.java
src/main/java/uk/gov/companieshouse/accounts/association/service/AssociationsService.java
src/test/java/uk/gov/companieshouse/accounts/association/common/TestDataManager.java
src/test/java/uk/gov/companieshouse/accounts/association/controller/UserCompanyAssociationTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/AssociationsServiceTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/UserCompanyAssociationTest.java
src/test/java/uk/gov/companieshouse/accounts/association/mapper/PreviousStatesCollectionMappersTest.java
src/test/java/uk/gov/companieshouse/accounts/association/mapper/PreviousStatesMapperTest.java
src/test/java/uk/gov/companieshouse/accounts/association/service/AssociationsServiceTest.java

Implemented endpoint to retrieve the previous states of an association.
IDVA6-2043

IDVA6-2043: Previous States

---

pom.xml
src/test/resources/application.properties

Upgraded to Mongo 7. Checked - Parent Pom is up-to-date, and central supressions hasn't been updated recently.
SIV-238

SIV-238: Upgraded to Mongo 7

---

src/main/java/uk/gov/companieshouse/accounts/association/configuration/WebSecurityConfig.java
src/main/java/uk/gov/companieshouse/accounts/association/controller/AssociationsListForCompanyController.java
src/main/java/uk/gov/companieshouse/accounts/association/controller/ControllerAdvice.java
src/main/java/uk/gov/companieshouse/accounts/association/controller/UserCompanyAssociation.java
src/main/java/uk/gov/companieshouse/accounts/association/exceptions/ForbiddenRuntimeException.java
src/main/java/uk/gov/companieshouse/accounts/association/filter/UserAuthenticationFilter.java
src/main/java/uk/gov/companieshouse/accounts/association/interceptor/RequestLifecycleInterceptor.java
src/main/java/uk/gov/companieshouse/accounts/association/models/Constants.java
src/main/java/uk/gov/companieshouse/accounts/association/models/SpringRole.java
src/main/java/uk/gov/companieshouse/accounts/association/models/context/RequestContextData.java
src/main/java/uk/gov/companieshouse/accounts/association/utils/RequestContextUtil.java
src/test/java/uk/gov/companieshouse/accounts/association/common/ComparisonUtils.java
src/test/java/uk/gov/companieshouse/accounts/association/controller/AssociationsListForCompanyControllerTest.java
src/test/java/uk/gov/companieshouse/accounts/association/controller/ControllerAdviceTest.java
src/test/java/uk/gov/companieshouse/accounts/association/controller/UserCompanyAssociationTest.java
src/test/java/uk/gov/companieshouse/accounts/association/filter/UserAuthenticationFilterTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/AssociationsListForCompanyControllerTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/UserCompanyAssociationTest.java
src/test/java/uk/gov/companieshouse/accounts/association/interceptor/RequestLifecycleInterceptorTest.java
src/test/java/uk/gov/companieshouse/accounts/association/service/EmailServiceTest.java
src/test/java/uk/gov/companieshouse/accounts/association/utils/RequestContextUtilTest.java

Updated code to enable admin users to retrieve and update associations.
SIV-261

SIV-261: Admin Portal Changes

---

pom.xml
suppress.xml

fixing security vulnerabilities
SIV-316

SIV-316: fixing security vulnerabilities

---

src/main/java/uk/gov/companieshouse/accounts/association/service/CompanyService.java

Removed redundant call to distinct method
SIV-339

SIV-339: Removed redundant call to distinct method

---

src/test/java/uk/gov/companieshouse/accounts/association/common/TestDataManager.java

creating addition test data using postman collection
SIV-333

SIV-333: creating addition test data using postman collection

---

pom.xml
src/main/java/uk/gov/companieshouse/accounts/association/configuration/InterceptorConfig.java
src/main/java/uk/gov/companieshouse/accounts/association/configuration/WebSecurityConfig.java
src/main/java/uk/gov/companieshouse/accounts/association/controller/AssociationsListForCompanyController.java
src/main/java/uk/gov/companieshouse/accounts/association/controller/UserCompanyAssociation.java
src/main/java/uk/gov/companieshouse/accounts/association/filter/UserAuthenticationFilter.java
src/main/java/uk/gov/companieshouse/accounts/association/interceptor/OAuth2AndKeyRequestLifecycleInterceptor.java
src/main/java/uk/gov/companieshouse/accounts/association/interceptor/OAuth2RequestLifecycleInterceptor.java
src/main/java/uk/gov/companieshouse/accounts/association/models/AssociationDao.java
src/main/java/uk/gov/companieshouse/accounts/association/models/Constants.java
src/main/java/uk/gov/companieshouse/accounts/association/models/SpringRole.java
src/main/java/uk/gov/companieshouse/accounts/association/models/context/RequestContextData.java
src/main/java/uk/gov/companieshouse/accounts/association/utils/RequestContextUtil.java
src/test/java/uk/gov/companieshouse/accounts/association/common/TestDataManager.java
src/test/java/uk/gov/companieshouse/accounts/association/controller/AssociationsListForCompanyControllerTest.java
src/test/java/uk/gov/companieshouse/accounts/association/controller/UserCompanyAssociationTest.java
src/test/java/uk/gov/companieshouse/accounts/association/controller/UserCompanyAssociationsTest.java
src/test/java/uk/gov/companieshouse/accounts/association/filter/UserAuthenticationFilterTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/UserCompanyAssociationTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/UserCompanyAssociationsTest.java
src/test/java/uk/gov/companieshouse/accounts/association/interceptor/OAuth2AndKeyRequestLifecycleInterceptorTest.java
src/test/java/uk/gov/companieshouse/accounts/association/interceptor/RequestLifecycleInterceptorTest.java
src/test/java/uk/gov/companieshouse/accounts/association/utils/AssociationsUtilTest.java

Updating the data model, and models and interfaces. Also adding support for API Key requests.
SIV-395

SIV-395: Added API Key boilerplate

---

pom.xml

Updated tomcat websocket subdependency, to resolve security vulnerabilities.
SIV-389

SIV-389: Fixed security vulnerabilities

---

src/main/java/uk/gov/companieshouse/accounts/association/controller/UserCompanyAssociation.java
src/main/java/uk/gov/companieshouse/accounts/association/utils/AssociationsUtil.java
src/test/java/uk/gov/companieshouse/accounts/association/controller/UserCompanyAssociationTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/UserCompanyAssociationTest.java
src/test/java/uk/gov/companieshouse/accounts/association/utils/AssociationsUtilTest.java

Updated PATCH endpoint to support unauthorised associations.
SIV-397

SIV-397: Updated PATCH endpoint to support unauthorised associations.

---

src/main/java/uk/gov/companieshouse/accounts/association/controller/AssociationsListForCompanyController.java
src/main/java/uk/gov/companieshouse/accounts/association/service/UsersService.java
src/test/java/uk/gov/companieshouse/accounts/association/controller/AssociationsListForCompanyControllerTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/AssociationsListForCompanyControllerTest.java
src/test/java/uk/gov/companieshouse/accounts/association/service/UsersServiceTest.java

Implemented requirements changes - fetch the user for user_email/user_id, depending on what's provided, and use the data.
SIV-396

Siv 396 unauthorised fetch associations for companies v2

---

pom.xml
src/main/java/uk/gov/companieshouse/accounts/association/configuration/WebSecurityConfig.java
src/main/java/uk/gov/companieshouse/accounts/association/controller/AssociationsListForCompanyController.java
src/test/java/uk/gov/companieshouse/accounts/association/controller/AssociationsListForCompanyControllerTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/AssociationsListForCompanyControllerTest.java

Enabled admin privileges for fetchAssociationsForCompany endpoint
SIV-494

SIV-494: Enabled admin privileges for fetchAssociationsForCompany endpoint

---

src/main/java/uk/gov/companieshouse/accounts/association/configuration/WebSecurityConfig.java
src/test/java/uk/gov/companieshouse/accounts/association/controller/UserCompanyAssociationTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/UserCompanyAssociationTest.java

endpoint change to support requests from API key
SIV-475

SIV-475: endpoint change to support requests from API key

---

src/main/java/uk/gov/companieshouse/accounts/association/controller/AssociationsListForCompanyController.java
src/main/java/uk/gov/companieshouse/accounts/association/controller/UserCompanyInvitations.java
src/main/java/uk/gov/companieshouse/accounts/association/service/AssociationsService.java
src/main/java/uk/gov/companieshouse/accounts/association/service/UsersService.java

remove user email details from logs
SIV-493

SIV-493: remove user email details from logs

---

src/main/java/uk/gov/companieshouse/accounts/association/models/email/EmailNotification.java

remove email from logs bug fix
SIV-553

SIV-553: remove email from logs bug fix

---

src/main/java/uk/gov/companieshouse/accounts/association/utils/StaticPropertyUtil.java
src/test/java/uk/gov/companieshouse/accounts/association/common/TestDataManager.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/AssociationsServiceTest.java
src/test/java/uk/gov/companieshouse/accounts/association/mapper/InvitationsCollectionMappersTest.java
src/test/java/uk/gov/companieshouse/accounts/association/service/AssociationsServiceTest.java

Updating the days since invite expires from 7 to 30 days
SIV-546

SIV-546: Updating the days since invite expires from 7 to 30 days

---

src/main/java/uk/gov/companieshouse/accounts/association/controller/UserCompanyAssociations.java
src/test/java/uk/gov/companieshouse/accounts/association/controller/UserCompanyAssociationsTest.java
src/test/java/uk/gov/companieshouse/accounts/association/integration/UserCompanyAssociationsTest.java

validating status and an enum on get associations endpoint
SIV-558

SIV-558: validating status and an enum on get associations endpoint

---

src/main/java/uk/gov/companieshouse/accounts/association/controller/AssociationsListForCompanyController.java

Removed misleading logs
SIV-814

SIV-814: Removed misleading logs
